version: '3'
services:
  lastfm-base:
    build:
      context: .
      dockerfile: base.dockerfile
    image: lastfm/base
    container_name: lastfm-base
  lastfm-srv:
    build:
      context: .
      dockerfile: srv.dockerfile
    image: lastfm/srv
    container_name: lastfm-srv
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ${DATA_PATH}:/.lastfm:rw
      - ${TLS_CERT_BASE}:/cert:ro
    networks:
      - lastfm-net
  lastfm-wrkr:
    build:
      context: .
      dockerfile: wrkr.dockerfile
    image: lastfm/wrkr
    container_name: lastfm-wrkr
    volumes:
      - ${DATA_PATH}:/.lastfm:rw
   
networks:
  lastfm-net: