version: '3'
services:
  lastfm-web:
    build:
      context: react/lastfm
    image: lastfm/web
    container_name: lastfm-web
    ports:
      - "80:3000"
      - "443:4000"
    networks:
      - lastfm-net
    environment:
      - BACKEND_HOST=lastfm-srv:${BACKEND_PORT}
      - TLS_CERT_REL=${TLS_CERT_REL}
    volumes:
      - "${TLS_CERT_BASE}:/cert"
    restart: always

networks:
  lastfm-net:
