package config

// Countries associates nationalities names with country names.
var Countries = map[string]string{
	"afghan":        "Afghanistan",
	"albanian":      "Albania",
	"algerian":      "Algeria",
	"argentinian":   "Argentina",
	"australian":    "Australia",
	"austrian":      "Austria",
	"bangladeshi":   "Bangladesh",
	"barbadian":     "Barbados",
	"belgian":       "Belgium",
	"bolivian":      "Bolivia",
	"batswana":      "Botswana",
	"brazilian":     "Brazil",
	"bulgarian":     "Bulgaria",
	"cambodian":     "Cambodia",
	"cameroonian":   "Cameroon",
	"canadian":      "Canada",
	"chilean":       "Chile",
	"chinese":       "China",
	"colombian":     "Colombia",
	"costa rican":   "Costa Rica",
	"croatian":      "Croatia",
	"cuban":         "Cuba",
	"czech":         "Czech Republic",
	"danish":        "Denmark",
	"dominican":     "Dominican Republic",
	"ecuadorian":    "Ecuador",
	"egyptian":      "Egypt",
	"salvadorian":   "El Salvador",
	"estonian":      "Estonia",
	"ethiopian":     "Ethiopia",
	"fijian":        "Fiji",
	"finnish":       "Finland",
	"french":        "France",
	"german":        "Germany",
	"ghanaian":      "Ghana",
	"greek":         "Greece",
	"guatemalan":    "Guatemala",
	"haitian":       "Haiti",
	"honduran":      "Honduras",
	"hungarian":     "Hungary",
	"icelandic":     "Iceland",
	"indian":        "India",
	"hindi":         "India",
	"indonesian":    "Indonesia",
	"iranian":       "Iran",
	"persian":       "Iran",
	"iraqi":         "Iraq",
	"irish":         "Ireland",
	"israeli":       "Israel",
	"italian":       "Italy",
	"jamaican":      "Jamaica",
	"japanese":      "Japan",
	"jordanian":     "Jordan",
	"kenyan":        "Kenya",
	"kurdish":       "Kurdistan",
	"kuwaiti":       "Kuwait",
	"lao":           "Laos",
	"laotain":       "Laos",
	"latvian":       "Latvia",
	"lebanese":      "Lebanon",
	"libyan":        "Libya",
	"lithuanian":    "Lithuania",
	"malaysian":     "Malaysia",
	"malay":         "Malaysia",
	"malian":        "Mali",
	"maltese":       "Malta",
	"mexican":       "Mexico",
	"mongolian":     "Mongolia",
	"moroccan":      "Morocco",
	"mozambican":    "Mozambique",
	"namibian":      "Namibia",
	"nepalese":      "Nepal",
	"nepali":        "Nepal",
	"dutch":         "Netherlands",
	"new zealand":   "New Zealand",
	"nicaraguan":    "Nicaragua",
	"nigerian":      "Nigeria",
	"norwegian":     "Norway",
	"pakistani":     "Pakistan",
	"panamanian":    "Panama",
	"paraguayan":    "Paraguay",
	"peruvian":      "Peru",
	"philippine":    "Philippines",
	"polish":        "Poland",
	"portuguese":    "Portugal",
	"puerto rican":  "Puerto Rico",
	"romanian":      "Romania",
	"russian":       "Russia",
	"saudi":         "Saudi Arabia",
	"senegalese":    "Senegal",
	"serbian":       "Serbia",
	"singaporean":   "Singapore",
	"slovak":        "Slovakia",
	"south african": "South Africa",
	"korean":        "South Korea",
	"spanish":       "Spain",
	"sri lankan":    "Sri Lanka",
	"sudanese":      "Sudan",
	"swedish":       "Sweden",
	"swiss":         "Switzerland",
	"syrian":        "Syria",
	"taiwanese":     "Taiwan",
	"tajikistani":   "Tajikistan",
	"thai":          "Thailand",
	"tongan":        "Tonga",
	"tunisian":      "Tunisia",
	"turkish":       "Turkey",
	"ukrainian":     "Ukraine",
	"emirati":       "United Arab Emirates",
	"british":       "United Kingdom",
	"english":       "United Kingdom",
	"scottish":      "United Kingdom",
	"welsh":         "United Kingdom",
	"american":      "United States",
	"uruguayan":     "Uruguay",
	"venezuelan":    "Venezuela",
	"vietnamese":    "Vietnam",
	"zambian":       "Zambia",
	"zimbabwean":    "Zimbabwe",
}
